### ISSUE TITLE
[Error]: Broken next/previous links due to single digit numbering scheme in filenames

### ISSUE THREAD

**Issue by k4r4b3y** [monerogarden/web#28]
### Error Description

The python script you use for adding `Previous / Next` links to individual markdown files behaves erroneously IF you use don't use a leading zero with your filenames.

### Link to the content

https://monero.garden/3-notes-for-humans/strings_attached

### Solution

Change your filenames to the following format:

3.01_[...]
3.02_[...]
3.03_[...]
[...]
3.09_[...]

you can keep the filenames with double digit order numbering untouched.

### Code of Conduct

- [X] I have searched for similar error reports
- [X] I have provided a clear and detailed explanation

**Comment by anhdres** [comment]
Applied the suggested changes and now seems to be fixed. Thanks!
